FROM continuumio/anaconda3
MAINTAINER Giuseppe Romano <romanog@mit.edu>

RUN apt-get update

RUN apt-get install -y libglu1-mesa libxcursor1 libxft-dev libxinerama-dev

RUN apt-get install -y vim

RUN conda update -n base -c defaults conda

RUN conda create -n openbte -c gromano -c conda-forge -c ostrokach-forge openbte==1.13 

RUN echo "source activate openbte" > ~/.bashrc
ENV PATH /opt/conda/envs/openbte/bin:$PATH


EXPOSE 8050







