
package:
  name: "openbte"
  version: "2.8"

source:
  url: ../dist/openbte-2.8.tar.gz
build:
        
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - mpi4py
    - numpy
    - pip
    - plotly
    - python >=3.6
    - pyvtk
    - scipy
    - gmsh
    - shapely
    - twisted  
    - pandas  
    - termcolor
    - unittest2
  run:
    - future
    - mpi4py
    - plotly
    - numpy
    - python >=3.6
    - pyvtk
    - scipy
    - shapely
    - termcolor
    - unittest2
    - gmsh
    - pyqt

test:
  imports:
    - openbte
about:
  home: The package home page
  license: GPLv3
  license_family: GPL3
  license_file: 
  summary: Boltzmann Transport Equation for Phonons
  doc_url: 
  dev_url:
  description: For Windows you'll need to install MSMPI. Install with conda install -c conda-forge -c gromano openbte

extra:
  recipe-maintainers:
    - romanodev
