#!/bin/sh

#
# Chainer/CuPy Installer for Google Colaboratory
# https://github.com/chainer/google-colaboratory
#


if ! nvidia-smi > /dev/null; then
    cat << '_EOF_'
********************************************************************************
GPU is not enabled!
Open "Runtime" > "Change runtime type" and set "Hardware accelerator" to "GPU".
********************************************************************************
_EOF_
    exit 1
fi


if [ -d /usr/local/cuda-10.0 ]; then
    # For CUDA 10.0 container
    set -ex
    apt -y -q install cuda-libraries-dev-10-0
    pip install -q "cupy-cuda100 ${CUPY_VERSION}" "chainer ${CHAINER_VERSION}"

elif [ -d /usr/local/cuda-9.2 ]; then
    # For CUDA 9.2 container
    set -ex
    apt -y -q install cuda-libraries-dev-9-2
    pip install -q "cupy-cuda92 ${CUPY_VERSION}" "chainer ${CHAINER_VERSION}"

elif [ -e /usr/lib/x86_64-linux-gnu/libcudart.so.8.0 ]; then
    # For CUDA 8.0 container
    set -ex
    apt -y -q install libcusparse8.0 libnvrtc8.0 libnvtoolsext1
    ln -snf /usr/lib/x86_64-linux-gnu/libnvrtc-builtins.so.8.0 /usr/lib/x86_64-linux-gnu/libnvrtc-builtins.so
    pip install -q "cupy-cuda80 ${CUPY_VERSION}" "chainer ${CHAINER_VERSION}"

else
    cat << '_EOF_'
********************************************************************************
CUDA version could not be detected!
Please file an issue at: https://github.com/chainer/google-colaboratory/issues/new
********************************************************************************
_EOF_
    exit 2
fi

set +ex
echo "Installation succeeded!"
