from openbte.geometry import *
from openbte.material import *
from openbte.solver import *


#Input: x (generated by "generate_grid")
#Output: kappa (compute by Solver)

mat = Material(model='gray',n_theta = 16, n_phi = 48,mfp=[10])

L = 10


geo = Geometry(type='porous/random_over_grid',
              lx = 10,ly = 10,
              nx = 10, ny = 10,np=10,
              step = L/10,
              automatic_periodic = False)
#------------------------------------------------


Solver(max_bte_iter = 10,multiscale=False)

kappa  = dd.io.load('solver.hdf5')['kappa'][-1]



